# Generated by Django 3.1.1 on 2020-10-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_nproj_treg'),
    ]

    operations = [
        migrations.AddField(
            model_name='nproj',
            name='div',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nproj',
            name='git',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
