# Generated by Django 3.1.1 on 2020-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201112_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Semester', models.CharField(max_length=100)),
                ('Roll_no', models.IntegerField()),
                ('Div', models.CharField(max_length=5)),
                ('Project_name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Teacher_username', models.CharField(max_length=100)),
                ('Project_description', models.CharField(max_length=100)),
                ('Git_link', models.URLField()),
                ('Project_members', models.CharField(max_length=200)),
                ('Output_Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
