# Generated by Django 3.0.5 on 2021-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_newproj'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_username', models.CharField(max_length=50)),
                ('project_score', models.IntegerField()),
                ('sem_average_marks', models.IntegerField()),
                ('test_score', models.IntegerField()),
                ('test_series_id', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('current_sem', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_username', models.CharField(max_length=50)),
                ('gaming_score', models.IntegerField()),
                ('aptitude_score', models.IntegerField()),
                ('coding_score', models.IntegerField()),
                ('avg_test_score', models.IntegerField()),
            ],
        ),
    ]
