# Generated by Django 3.0.5 on 2021-12-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_studentsprofile_testseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
