# Generated by Django 3.0.5 on 2022-01-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='teacher_username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='testkey',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
