# Generated by Django 3.0.5 on 2022-01-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20220102_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='testkey',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
