# Generated by Django 3.0.5 on 2022-01-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_testscore_testkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='quizname',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
