# Generated by Django 3.0.5 on 2022-01-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_questionbank_quizname'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='endrosment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
