# Generated by Django 3.0.5 on 2022-01-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_grade_endrosment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='endrosment',
        ),
    ]
