# Generated by Django 3.0.5 on 2022-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_grade_endrosment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='endroment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
