# Generated by Django 3.0.5 on 2022-01-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_grade_endroment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='endroment',
            new_name='endorsement',
        ),
    ]
