# Generated by Django 3.0.5 on 2022-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20220103_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsprofile',
            name='test_score',
        ),
        migrations.RemoveField(
            model_name='studentsprofile',
            name='test_series_id',
        ),
        migrations.AlterField(
            model_name='studentsprofile',
            name='student_id',
            field=models.FloatField(),
        ),
    ]
