# Generated by Django 3.0.5 on 2022-01-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20220105_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproj',
            name='Project_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nproj',
            name='desc',
            field=models.TextField(),
        ),
    ]
