# Generated by Django 3.0.5 on 2022-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20220105_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='eq',
            field=models.IntegerField(default=0),
        ),
    ]
